apiVersion: deploy.cloud.google.com/v1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: worker
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      containers:
        - name: airflow-worker
          image: <your_docker_image>
          env:
            - name: AIRFLOW_HOME
              value: /airflow
            - name: GIT_SSH_COMMAND
              value: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://<your_db_user>:<your_db_password>@<your_db_host>:<your_db_port>/<your_db_name>
          volumeMounts:
            - name: airflow-dags
              mountPath: /airflow/dags
            - name: airflow-config
              mountPath: /airflow/config
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 2Gi
      volumes:
        - name: airflow-dags
          gcsfuse:
            bucket: <your_gcs_bucket>
            prefix: /dags
        - name: airflow-config
          configMap:
            name: airflow-config
