name: Build and Deploy to GKE

on: 
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_SA_PROJECT_ID }}
  GKE_CLUSTER: airflow-cluster    # Add your cluster name here.
  GKE_ZONE: europe-central2-a	  # Add your cluster zone here.
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_SA_PROJECT_ID }}

    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GCP_SA_KEY }}


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        export SCHEDULER_POD=$(kubectl get pods -n airflow | grep scheduler | awk '{print $1}')
        export WORKER_POD=$(kubectl get pods -n airflow | grep worker | awk '{print $1}')
        kubectl cp /home/wannatestemail124/sa_key.json my-airflow-worker-0:/opt/airflow -n airflow
        kubectl exec -it $WORKER_POD -n airflow -- /home/airflow/.local/bin/pip install -r /opt/airflow/dags/repo/requirements.txt
        kubectl exec -it $SCHEDULER_POD -n airflow -- /home/airflow/.local/bin/pip install -r /opt/airflow/dags/repo/requirements.txt
        

